name: automerge

on:
  pull_request_review:
    types: [submitted]

defaults:
  run:
    shell: bash

jobs:
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
          MERGE_LABELS: "auto-sync"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "{pullRequest.title} (#{pullRequest.number})"
          MERGE_REQUIRED_APPROVALS: "1"
          UPDATE_LABELS: "auto-sync"
          UPDATE_METHOD: "rebase"
